
export const metadata = {
  title: 'Cart Page',
  description: 'Generated by Cart Page',
}

export default function CartLayout({ children }) {
  return (
            <div>
                    <aside>
                        <ul>
                            <li>Eternal 1</li>
                            <li>Eternal 1</li>
                        </ul>
                    </aside>
                    {children}
            </div>
  )
}
